pdfConfig: !pdfConfig
  compressed: false
  author: "Jeff Konnen"
  subject: "map.geoportail.lu Print"
  creator: "Mapfish Print"

throwErrorOnExtraParameters: true

templates:
  A4 portrait: !template
    pdfConfig: !pdfConfig
      title: "A4 Portrait by geoportail.lu"
      keywords: ["map"]
    reportTemplate: a4_portrait.jrxml
    attributes:
      name: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      dataOwner: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 470
        height: 650
      lang: !string {}
      legend: !datasource
        attributes:
            name: !string {}
        default: []
      scalebar: !scalebar
        width: 150
        height: 30
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
  A4 landscape: !template
    pdfConfig: !pdfConfig
      title: "A4 Landscape by geoportail.lu"
      keywords: ["map"]
    reportTemplate: a4_landscape.jrxml
    attributes:
      name: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      dataOwner: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 715
        height: 395
      lang: !string {}
      legend: !datasource
        attributes:
            name: !string {}
        default: []
      scalebar: !scalebar
        width: 150
        height: 30
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
  A3 portrait: !template
    pdfConfig: !pdfConfig
      title: "A3 Portrait by geoportail.lu"
      keywords: ["map"]
    reportTemplate: a3_portrait.jrxml
    attributes:
      name: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      dataOwner: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 715
        height: 975
      lang: !string {}
      legend: !datasource
        attributes:
            name: !string {}
        default: []
      scalebar: !scalebar
        width: 230
        height: 40
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
  A3 landscape: !template
    pdfConfig: !pdfConfig
      title: "A3 Landscape by geoportail.lu"
      keywords: ["map"]
    reportTemplate: a3_landscape.jrxml
    attributes:
      name: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      dataOwner: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 1064
        height: 640
      lang: !string {}
      legend: !datasource
        attributes:
            name: !string {}
        default: []
      scalebar: !scalebar
        width: 230
        height: 40
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
  A2 portrait: !template
    pdfConfig: !pdfConfig
      title: "A2 Portrait by geoportail.lu"
      keywords: ["map"]
    reportTemplate: a2_portrait.jrxml
    attributes:
      name: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      dataOwner: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 1064
        height: 1475
      lang: !string {}
      legend: !datasource
        attributes:
            name: !string {}
        default: []
      scalebar: !scalebar
        width: 230
        height: 40
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
  A2 landscape: !template
    pdfConfig: !pdfConfig
      title: "A2 Landscape by geoportail.lu"
      keywords: ["map"]
    reportTemplate: a2_landscape.jrxml
    attributes:
      name: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      dataOwner: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 1558
        height: 985
      lang: !string {}
      legend: !datasource
        attributes:
            name: !string {}
        default: []
      scalebar: !scalebar
        width: 230
        height: 40
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
  A1 portrait: !template
    pdfConfig: !pdfConfig
      title: "A1 Portrait by geoportail.lu"
      keywords: ["map"]
    reportTemplate: a1_portrait.jrxml
    attributes:
      name: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      dataOwner: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 1558
        height: 2175
      lang: !string {}
      legend: !datasource
        attributes:
            name: !string {}
        default: []
      scalebar: !scalebar
        width: 230
        height: 40
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
  A1 landscape: !template
    pdfConfig: !pdfConfig
      title: "A1 Landscape by geoportail.lu"
      keywords: ["map"]
    reportTemplate: a1_landscape.jrxml
    attributes:
      name: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      dataOwner: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 2255
        height: 1482
      lang: !string {}
      legend: !datasource
        attributes:
            name: !string {}
        default: []
      scalebar: !scalebar
        width: 230
        height: 40
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
  A0 portrait: !template
    pdfConfig: !pdfConfig
      title: "A0 Portrait by geoportail.lu"
      keywords: ["map"]
    reportTemplate: a0_portrait.jrxml
    attributes:
      name: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      dataOwner: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 2254
        height: 3155
      lang: !string {}
      legend: !datasource
        attributes:
            name: !string {}
        default: []
      scalebar: !scalebar
        width: 230
        height: 40
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
  A0 landscape: !template
    pdfConfig: !pdfConfig
      title: "A0 Landscape by geoportail.lu"
      keywords: ["map"]
    reportTemplate: a0_landscape.jrxml
    attributes:
      name: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      dataOwner: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 3241
        height: 2173
      lang: !string {}
      legend: !datasource
        attributes:
            name: !string {}
        default: []
      scalebar: !scalebar
        width: 230
        height: 40
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
